-- ============================================
-- Add comprehensive knowledge to knowledge_base
-- Source: Scraped from official LBSCEK website (lbscek.ac.in) on 2026-02-25
-- Covers: Leadership, Departments, Admission, Fees, Hostel, Placements,
--         Library, Bus Service, IEDC, Student Clubs, Academic Regulations
-- ============================================

INSERT INTO knowledge_base (section_key, section_title, content, section_order) VALUES

-- ─────────────────────────────────────────────────
-- 12. College Leadership
-- ─────────────────────────────────────────────────
('leadership', '12. College Leadership', E'## 12. College Leadership\n\n### Director\n- **Name:** Prof. (Dr.) M. Abdul Rahiman\n- **Phone:** 0471-2324396\n- **Email:** director.lbs@kerala.gov.in\n- **Profile:** Dr. M Abdul Rahiman is the Director of LBS Centre for Science & Technology. He was the First Batch student of LBS College of Engineering. He served as the first Pro-Vice-Chancellor of APJ Abdul Kalam Technological University (KTU), Kerala. He was the Managing Director of Kerala State Centre for Advanced Printing and Training (C-APT). He also served as Director, AICTE (All India Council for Technical Education). He is a Ph.D. graduate in Computer Science & Engineering, with PGDHRM and MBA degrees. He has published over 100 papers in academic journals.\n- **Website:** www.lbscentre.kerala.gov.in\n\n### Principal\n- **Name:** Prof. (Dr.) Mohammad Sekoor T\n- **Phone:** 04994-250290\n- **Email:** shek117@lbscek.ac.in / principal@lbscek.ac.in\n- **Qualification:** M.Tech in Heat Power Engineering (NIT Surathkal), Ph.D. in Analytical and Numerical Modeling of Compact Heat Exchangers (NIT Surathkal)\n\n### Key Administrative Contacts\n- **Administrative Officer:** Sri. Mr. Ajesh S — Tel: +91 9495310477, Email: administrativeofficer@lbscek.ac.in\n- **Dean Academics:** Dr. Praveen Kumar K — Tel: +91 9447375156, Email: praveenkodoth@lbscek.ac.in\n- **Dean Student Affairs:** Dr. Vinodu George — Tel: +91 9447386534, Email: vinodu@lbscek.ac.in', 12),

-- ─────────────────────────────────────────────────
-- 13. Admission Process (Detailed)
-- ─────────────────────────────────────────────────
('admission_process_detail', '13. Admission Process (Detailed)', E'## 13. Admission Process (Detailed)\n\n### B.Tech Admission\n- **Affiliation:** APJ Abdul Kalam Technological University (KTU) from 2015-16 onwards\n- **Total Annual Intake:** ~500 students across 6 B.Tech programs\n- **85% seats:** Allotted by Commissioner for Entrance Examination (CEE), Govt. of Kerala from KEAM rank list\n- **15% seats:** Reserved for NRI (Non-Resident Indian) candidates\n- **KEAM Website:** https://www.cee.kerala.gov.in/\n\n### Academic Eligibility (B.Tech - KEAM)\n- Must pass Higher Secondary Examination (Kerala) or equivalent\n- Minimum **50% marks in Mathematics** separately\n- Minimum **50% marks in Maths + Physics + Chemistry/Biotechnology/CS/Biology** combined\n\n### Lateral Entry (Second Year)\n- For diploma holders in Engineering from Board of Technical Examinations\n- Minimum **50% marks** in final diploma examination\n- Allotment done by **LBS Centre for Science & Technology, Thiruvananthapuram**\n- Based on rank list from Lateral Entry Test (LET)\n\n### B.Tech Seat Allocation (2024-2025)\n- **Merit Quota (Lower Fee):** Rs. 45,000 per year\n- **NRI Quota:** Separate fee structure\n- **Additional 10% seats** allotted from KEAM rank list under Tuition Fee Waiver scheme (for women, economically backward, physically handicapped meritorious students)\n\n### M.Tech Admission\n- **Program:** M.Tech in Computer Science and Information Security\n- **Intake:** 18 students\n- **75% Merit Quota:** Allotted by Director of Technical Education (DTE)\n- **25% Sponsored Quota:** For candidates from Educational/Research institutions (min. 2 years experience required)\n- **Selection:** Based on GATE score, or aggregate marks of B.Tech 8 semesters\n- **Eligibility:** B.Tech in Computer Science & Engineering or Information Technology\n\n### Admission Enquiry Contacts\n1. Dr. Mohammad Sekoor T, Principal — Tel: 04994 250 290, Email: principal@lbscek.ac.in\n2. Sri. Mr. Ajesh S, Administrative Officer — Tel: +91 9495310477\n3. Dr. Praveen Kumar K, Dean Academics — Tel: +91 9447375156\n4. Dr. Vinodu George, Dean Student Affairs — Tel: +91 9447386534\n5. Dr. Anil Kumar B.C, Associate Professor, ME — Tel: +91 9496358213', 13),

-- ─────────────────────────────────────────────────
-- 14. Fee Structure
-- ─────────────────────────────────────────────────
('fee_structure_detail', '14. Fee Structure', E'## 14. Fee Structure\n\n### B.Tech Fee Structure (2025-26)\n- **Regular B.Tech:** See official document at https://lbscek.ac.in/wp-content/uploads/2025/07/lbscek_btech_fee_202526.pdf\n- **NRI Admissions:** See https://lbscek.ac.in/wp-content/uploads/2025/05/BTechNRIFee2025.pdf\n- **Lateral Entry:** See https://lbscek.ac.in/wp-content/uploads/2025/06/let-2025-feestructure.pdf\n- **Merit Quota Fee (approximate):** Rs. 45,000 per year\n\n### M.Tech Fee Structure (2025-26)\n- See official document at https://lbscek.ac.in/wp-content/uploads/2025/07/MTechFee2025.pdf\n\n### Fee Payment Links\n- **Annual/Admission Fee:** https://lbscek.ac.in/annual-admission-fee/\n- **Exam/Other Fee Payment:** https://lbscek.ac.in/exam-other-fee-payment/\n- **Semester Registration Online:** https://lbscek.ac.in/semester-registration-online/\n- **Hostel Rent:** https://lbscek.ac.in/hostel-rent/', 14),

-- ─────────────────────────────────────────────────
-- 15. Department of Computer Science & Engineering
-- ─────────────────────────────────────────────────
('dept_cse', '15. Department of Computer Science & Engineering', E'## 15. Department of Computer Science & Engineering\n\n- **Established:** 1993\n- **Email:** csed@lbscek.ac.in\n- **Research Centre:** Recognized under KTU since 2015\n\n### Vision\nTo be a renowned centre for education, research, and innovation in the frontier areas of Computer Science and Engineering.\n\n### Mission\n- Establish and maintain an operational environment to acquire, impart, create and apply knowledge in CSE and interdisciplinary areas\n- Serve as a resource centre for innovation in design & development of software and hardware solutions\n- Inculcate leadership qualities, professional ethics and a sense of social commitment\n\n### Programs Offered\n1. **B.Tech in Computer Science & Engineering** — 4 years\n2. **B.Tech in Information Technology** — 4 years (started 2000)\n3. **B.Tech in Computer Science & Business Systems (CSBS)** — 4 years\n4. **B.Tech in CSE (Artificial Intelligence & Data Science)** — 4 years\n5. **M.Tech in Computer Science & Information Security** — 2 years (started 2013)\n\n### Highlights\n- Numerous university rank holders over the years\n- Students placed in Central/State/PSUs and multinational companies\n- Faculty actively engaged in consultancy and training programs\n- Close ties with leading industries and educational institutions', 15),

-- ─────────────────────────────────────────────────
-- 16. Department of Mechanical Engineering
-- ─────────────────────────────────────────────────
('dept_me', '16. Department of Mechanical Engineering', E'## 16. Department of Mechanical Engineering\n\n- **Established:** 1993\n- **Email:** med@lbscek.ac.in\n- **Program:** B.Tech in Mechanical Engineering (4 years)\n\n### Vision\nExcel individually and collectively in Mechanical Engineering to generate, innovate and disseminate the knowledge for the development of society.\n\n### HOD\n- **Dr. Manoj Kumar C.V.** — Associate Professor, Mobile: 9895663157, Email: cvmanojkumar@lbscek.ac.in\n\n### Faculty (Teaching Staff)\nDr. Manoj Kumar C.V., Prof Mahesh P V, Dr. Swaraj Kumar B., Dr. Anil Kumar B.C., Prof. Jowhar Mubarak, Prof. Vinod O.M., Prof. Sreejith M, Prof. Prajina N.V., Prof. Mukul Joseph, Prof. Latheesh Bharathan, Prof. Aswanth K\n\n### Facilities\n- Independent reference library with 500+ volumes\n- Well-equipped laboratories for project works on latest developments', 16),

-- ─────────────────────────────────────────────────
-- 17. Department of Electrical & Electronics Engineering
-- ─────────────────────────────────────────────────
('dept_eee', '17. Department of Electrical & Electronics Engineering', E'## 17. Department of Electrical & Electronics Engineering\n\n- **Established:** 1993\n- **Email:** eed@lbscek.ac.in\n- **YouTube:** https://www.youtube.com/@EEEDepartmentLBSCEK\n- **Program:** B.Tech in EEE — Intake: 66 students (including 6 lateral entry)\n\n### Vision\nTo nurture world class Electrical and Electronics Engineers contributing to the society at large with emphasis on sustainable technologies.\n\n### HOD\n- **Prof. Jayakumar M.** — Associate Professor and Head of Department, Mobile: 9446463953\n\n### Consultancy Services\n- Testing of large capacity UPS systems\n- Precise measurement using Power Analyzer, Digital earth tester\n- True RMS measurements of electrical parameters\n- Testing of streetlights for various Panchayats\n\n### Distinguished Alumni\nGraduates hold positions in NTPC, KSEB, HAL, DRDO, ISRO, Electrical Inspectorate, Railways, Civil Services, and multinationals\n\n### Library\n- Department library with 300+ titles and 20 IS (Indian Standard) codes', 17),

-- ─────────────────────────────────────────────────
-- 18. Department of Electronics & Communication Engineering
-- ─────────────────────────────────────────────────
('dept_ece', '18. Department of Electronics & Communication Engineering', E'## 18. Department of Electronics & Communication Engineering\n\n- **Established:** 1993\n- **Email:** eced@lbscek.ac.in\n- **Program:** B.Tech in ECE\n- **HOD:** Dr. Mary Reena K.E.\n- **Faculty:** 21 members (teaching + non-teaching), 7 PhD holders\n\n### Vision\nTo evolve as a renowned centre in pursuit of professional education and research in the domain of Electronics and Communication Engineering.\n\n### Specializations\nVLSI, Signal Processing, Communications, Embedded Systems\n\n### Laboratories (8)\nElectronics Workshop, Electronic/Integrated Circuits, Digital Electronics, Microprocessor & Microcontroller, Communications, Projects & Research labs\n\n### Industry Partnerships\n- **C-DAC** (Centre for Development of Advanced Computing), Technopark, Trivandrum\n- **KELTRON** (Kerala State Electronics Development Corporation)\n\n### Notable Achievements\n- Secured prestigious "LoRa in a Box" project from ICFOSS, Trivandrum\n- Funded projects from KTU, KSCSTE, and CeDS\n- Students won KSCSTE Best Student Project awards (twice)\n- Additional skill programs: AI/ML, Robotic Process Automation, Google Cloud', 18),

-- ─────────────────────────────────────────────────
-- 19. Department of Civil Engineering
-- ─────────────────────────────────────────────────
('dept_civil', '19. Department of Civil Engineering', E'## 19. Department of Civil Engineering\n\n- **Established:** 2008\n- **Email:** ced@lbscek.ac.in\n- **YouTube:** https://youtube.com/@civiengineeringdepartmentl3377\n- **Program:** B.Tech in Civil Engineering — Intake: 60 students\n- **HOD:** Dr. Anjali M S — Mobile: 9496251434, Email: anjalims@lbscek.ac.in\n\n### Vision\nTo become a distinguished centre for nurturing socially committed and technically skilled Civil Engineering professionals with an aptitude for research and life-long learning.\n\n### Consultancy Wing\nUndertakes consultancy projects from Government agencies and other clients with active participation of staff and students.\n\n### Student Chapter\nIndian Geotechnical Society (IGS) student chapter enables networking with practicing geotechnical engineers and academicians.', 19),

-- ─────────────────────────────────────────────────
-- 20. Hostel Facilities
-- ─────────────────────────────────────────────────
('hostel_details', '20. Hostel Facilities', E'## 20. Hostel Facilities\n\n- **Total Hostels:** 6 (3 in-campus + 3 out-campus)\n- **Accommodation:** Separate boys and girls hostels\n- **Email:** warden@lbscek.ac.in\n- **Amenities:** Fully furnished, 24x7 WiFi, indoor games, dedicated mess in each hostel\n- **Guest rooms** with standard facilities also available on campus\n- **Hostel Monitoring Committee:** Prof. Jowhar Mubarak, Asst. Prof ME\n\n### Hostel Timings\n- **Men''s Hostels (MH1, MH2, MH3):** Entrance closes at 9:00 PM\n- **Men''s Hostel (MH4 - First Year):** Entrance closes at 8:00 PM\n- **Ladies Hostel:** Entrance closes at 6:00 PM\n\n### Key Rules\n- Priority allotment based on distance from hometown\n- Minimum allotment period: 1 year\n- Ragging is strictly banned (reported to police immediately)\n- Alcohol/narcotics strictly prohibited\n- Electric cookers, high-volume speakers not allowed\n- Visitors must enter details in visitors register\n- Movement register required for outings after 10:30 PM\n- ID card must be carried at all times\n\n### Mess System\n- Elected mess committee each month\n- Menu published in advance by mess committee\n- Maximum 15 days mess cut per month (minimum 5 continuous days)\n- Mess fine: Rs. 100 after due date, then Rs. 10 per day\n- Guests can take food on payment basis\n\n### Hostel Fee Payment\n- **Pay Hostel Rent:** https://lbscek.ac.in/hostel-rent/', 20),

-- ─────────────────────────────────────────────────
-- 21. Career Guidance & Placement Unit (CGPU)
-- ─────────────────────────────────────────────────
('placements_detail', '21. Career Guidance & Placement Unit (CGPU) — Placements', E'## 21. Career Guidance & Placement Unit (CGPU) — Placements\n\n- **Email:** cgpu@lbscek.ac.in / sarith@lbscek.ac.in\n- **Website:** https://lbscek.ac.in/career-guidance-placement-unit-cgpu/\n\n### About CGPU\nThe CGPU orchestrates year-round training activities to prepare students for campus selection programs and collaborates with diverse industries for recruitment. It focuses on molding engineering graduates into adept professionals, offering campus interviews, job placements, and training programs. The cell also organizes workshops on personality development, communication, interview skills, and presentation skills.\n\n### Placement Statistics (Year-wise)\n| Year | Students Placed |\n|------|----------------|\n| 2023 | 115 |\n| 2022 | 140 |\n| 2021 | 125 |\n| 2020 | 125 |\n| 2019 | 112 |\n| 2018 | 78 |\n| 2017 | 111 |\n| 2016 | 105 |\n| 2015 | 75 |\n| 2014 | 70 |\n\n### Placement Training Reports\n- 2023-24: http://lbscek.ac.in/wp-content/uploads/2024/04/Placement-Training-Report-2023-24-2.pdf\n- 2022-23: http://lbscek.ac.in/wp-content/uploads/2024/04/Placement-Training-Report-2022-23-1.pdf\n- 2021-22: http://lbscek.ac.in/wp-content/uploads/2024/04/Placement-Training-Report-2021-22-1.pdf\n- 2020-21: http://lbscek.ac.in/wp-content/uploads/2024/04/Placement-Training-Report-2020-21-1.pdf\n\n### Services Offered\n- Campus interviews and job placements\n- Personality development workshops\n- Communication & soft skills training\n- Interview and presentation skills workshops\n- Orientation programs for freshers\n- Alumni engagement sessions', 21),

-- ─────────────────────────────────────────────────
-- 22. Central Library
-- ─────────────────────────────────────────────────
('library_detail', '22. Central Library', E'## 22. Central Library\n\n- **Email:** library@lbscek.ac.in\n- **Built-up Area:** 15,000 sq. ft.\n- **Total Books:** 30,043 volumes\n- **Titles:** 9,400+ different titles\n- **Librarian:** Mr. Vinod Kumar K.T.\n- **Library Attender:** Mr. Balachandran K.P.\n- **OPAC:** http://www.lbsce.libsoft.org/\n\n### Working Hours\n- **Reference Section:** 9:00 AM – 5:30 PM\n- **Circulation Section:** 9:00 AM – 4:30 PM\n\n### Borrowing Limits\n- **UG Students:** 4 books at a time\n- **PG Students:** 7 books at a time\n- **Loan Period:** 30 days (overdue fine applies)\n- **Lost Book Penalty:** 3x cost of book if not replaced\n\n### Services\n- Library Reference Service\n- Document Delivery Service\n- Internet Search Facility\n- OPAC (Online Public Access Catalogue)\n- Digital Library Access\n- Book Bank Facility\n- Reprographic Facility\n- Newspaper Clipping\n- Current Awareness Services\n- Information Alert\n- Inter Library Loan\n\n### Circulation System\n- Fully automated with barcode technology\n- Borrower''s tickets must be renewed at start of every odd semester\n\n### Digital Resources\n- Online journal access via Intranet Digital Library System\n- National Digital Library access\n- DELNET (Delhi Library Network) membership\n- E-Books available\n- CD-ROMs and Audio-Visual collection', 22),

-- ─────────────────────────────────────────────────
-- 23. Bus Service & Transportation
-- ─────────────────────────────────────────────────
('bus_service_detail', '23. Bus Service & Transportation', E'## 23. Bus Service & Transportation\n\n- **Website:** https://lbscek.ac.in/bus-service/\n\n### Bus Committee Members\n- Sri K. Sarathchandran Unnithan, Administrative Officer\n- Sri. Aneesh Mohan C S, Head Accountant\n- Prof. Jowahar Mubarak, Hostel Warden\n- Prof. Arun S Mathew, PTA Joint Secretary\n- College Union Vice Chairperson\n- Sri. Kumaran K, Driver\n- Sri. Biju T K, Driver\n- Two student representatives\n\n### Location\n- College is located at Povval, Muliyar P.O., 12 km from Kasaragod town\n- Bus service operates for students commuting from Kasaragod and nearby areas', 23),

-- ─────────────────────────────────────────────────
-- 24. IEDC (Innovation & Entrepreneurship)
-- ─────────────────────────────────────────────────
('iedc_detail', '24. Innovation and Entrepreneurship Development Centre (IEDC)', E'## 24. Innovation and Entrepreneurship Development Centre (IEDC)\n\n- **Established:** 2016 (under Kerala Startup Mission)\n- **Website:** https://lbscek.ac.in/iedc/\n\n### Objectives\n- Guidance on all facets of establishing enterprises\n- Foster entrepreneurial culture within the institution\n- Innovation-driven entrepreneurship through student projects\n- Address challenges of Small & Medium Enterprises (SMEs)\n\n### Functions\n- Entrepreneurship Awareness Camps & Development Programs\n- Faculty Development Programs & Skill Development Programs\n- Mentorship programs connecting entrepreneurs with students\n- Outreach to nearby schools and polytechnics\n\n### Startups Born from LBSCEK\nExinosis Technologies, SE-Mentor Solutions, Krifal IT Ventures, Zyxware Technologies, Foradian Technologies, Innoz Technologies, Quest Technologies, Ichanical Technologies, Spinov Technologies, Quinoid Business Solution, Kemoz Technologies, Forren Technologies, Quadloops Technologies, Fobeams Technologies, Dodo Technologies, Sparteqz Technologies, App Motions Technologies, I-Maps Technologies, AiantZorb Technologies, Quartzbit, and more (39+ startups total)\n\n### Programs Conducted\n- Idea pitching sessions\n- Hackathons (Carbon Zero Challenge, Smart India Hackathon)\n- Workshops on robotics, web development, career skills\n- YIP (Young Innovators Programme) orientations', 24),

-- ─────────────────────────────────────────────────
-- 25. Student Clubs & Communities
-- ─────────────────────────────────────────────────
('student_clubs', '25. Student Clubs & Communities', E'## 25. Student Clubs & Communities\n\n### TinkerHub\n- Community of tinkerers, makers & students passionate about innovation\n- Activities: Code-a-Pokkalam, Web Design Bootcamp, Python workshops, Git/GitHub sessions, Overnight Hackathons\n- Website: https://www.tinkerhub.org/\n\n### MuLearn\n- Synergic philosophy of education through mutual learning via micro peer groups\n- Website: https://mulearn.org/\n\n### Microsoft Learn Student Ambassador (MLSA)\n- Global community empowering students to share passion for technology\n- Activities: Student Summit Watch Party, Azure AI Fundamentals Challenge, Azure Fundamentals Challenge\n- Website: https://mvp.microsoft.com/studentambassadors\n\n### IEEE Student Branch\n- Active professional chapter for electronics and computer engineering students\n- Website: https://lbscek.ac.in/ieee/\n\n### FOSS (Free & Open Source Software) Community\n- Promotes open source software development and contribution\n\n### NSS (National Service Scheme)\n- Community service and social activities\n- Website: https://lbscek.ac.in/national-service-scheme/\n\n### GDSC (Google Developer Student Club)\n- Google-backed developer club for tech skill building\n\n### College Union\n- Elected student body organizing cultural and academic events\n- Website: https://lbscek.ac.in/college-union/', 25),

-- ─────────────────────────────────────────────────
-- 26. Academic Programs Summary
-- ─────────────────────────────────────────────────
('academic_programs', '26. Academic Programs Summary', E'## 26. Academic Programs Summary\n\n### B.Tech Programs (4-year, KTU affiliated)\n| Program | Department | Intake |\n|---------|-----------|--------|\n| Computer Science & Engineering | CSE | ~60 |\n| Information Technology | CSE | ~60 |\n| Computer Science & Business Systems | CSE | ~60 |\n| CSE (Artificial Intelligence & Data Science) | CSE | ~60 |\n| Mechanical Engineering | ME | ~60 |\n| Electrical & Electronics Engineering | EEE | 66 |\n| Electronics & Communication Engineering | ECE | ~60 |\n| Civil Engineering | CE | 60 |\n\n### M.Tech Programs (2-year, KTU affiliated)\n| Program | Department | Intake |\n|---------|-----------|--------|\n| Computer Science & Information Security | CSE | 18 |\n\n### Total Departments: 5 + Applied Science + Physical Education\n1. Computer Science & Engineering (CSE)\n2. Mechanical Engineering (ME)\n3. Electrical & Electronics Engineering (EEE)\n4. Electronics & Communication Engineering (ECE)\n5. Civil Engineering (CE)\n6. Applied Science (AS)\n7. Physical Education (PE)', 26),

-- ─────────────────────────────────────────────────
-- 27. Academic Regulations & Rules
-- ─────────────────────────────────────────────────
('academic_regulations', '27. Academic Regulations & Rules', E'## 27. Academic Regulations & Rules\n\n### University Affiliation\n- Affiliated to **APJ Abdul Kalam Technological University (KTU)** since 2015-16\n- All B.Tech and M.Tech programs follow KTU syllabus and regulations\n- KTU Website: http://ktu.edu.in/\n\n### Working Hours\n- **Class Timings:** 9:15 AM – 4:00 PM\n- **Office Hours:** 9:00 AM – 5:00 PM (Mon–Fri), 9:00 AM – 1:00 PM (Sat)\n\n### Anti-Ragging\n- Anti-Ragging Cell is active on campus\n- Ragging is strictly banned; any case is reported to police immediately\n- Website: https://lbscek.ac.in/anti-ragging-cell/\n\n### Grievance Redressal\n- Grievance Cell available for student complaints\n- Website: https://lbscek.ac.in/grievance-cell/\n\n### Quality Assurance\n- Internal Quality Assurance Cell (IQAC) ensures continuous quality improvement\n- Website: https://lbscek.ac.in/internal-quality-assurance-cell-iqac/\n\n### NBA Accreditation\n- NBA accreditation process in progress\n- Website: https://lbscek.ac.in/nba-accreditation-process/', 27),

-- ─────────────────────────────────────────────────
-- 28. Campus Facilities (Detailed)
-- ─────────────────────────────────────────────────
('campus_facilities', '28. Campus Facilities (Detailed)', E'## 28. Campus Facilities (Detailed)\n\n### Campus\n- **Area:** 52 acres of lush green campus\n- **Location:** Povval, Muliyar P.O., Kasaragod, Kerala - 671542 (12 km from Kasaragod town)\n\n### Academic Facilities\n- **Central Library:** 30,043 books, 15,000 sq ft, fully automated\n- **Digital Library:** Online journals, DELNET, National Digital Library\n- **Central Computing Facility:** https://lbscek.ac.in/central-computing-facility/\n- **AICTE IDEA Lab:** Makerspace for innovation — https://lbscek.ac.in/aicte-idea-lab/\n- **Fab Lab:** Fabrication laboratory — https://lbscek.ac.in/fab-lab-facility/\n- **Skill Delivery Platform:** https://lbscek.ac.in/skill-delivery-platform/\n\n### Student Services\n- **Hostel:** 6 hostels (boys & girls), fully furnished, 24x7 WiFi\n- **Bus Service:** Campus bus connecting Kasaragod town\n- **ATM Facility:** On-campus ATM — https://lbscek.ac.in/atm-facility/\n- **Student Co-Operative Society:** https://lbscek.ac.in/student-co-operative-society/\n- **Canteen / Mess:** Dedicated mess in each hostel\n\n### Extra-Curricular\n- **CGPU:** Career Guidance & Placement Unit\n- **IEDC:** Innovation & Entrepreneurship Development Centre\n- **NSS:** National Service Scheme\n- **PTA:** Parent Teacher Association\n- **College Union:** Student-elected body\n- **IEEE, TinkerHub, MuLearn, MLSA, FOSS, GDSC** student chapters', 28),

-- ─────────────────────────────────────────────────
-- 29. Contact Information (Detailed)
-- ─────────────────────────────────────────────────
('contact_detail', '29. Contact Information (Detailed)', E'## 29. Contact Information (Detailed)\n\n### College Address\nLBS College of Engineering\nPovval, Muliyar P.O.\nKasaragod, Kerala - 671542\nIndia\n\n### Phone Numbers\n- **Office:** +91-4994-256300, +91-4994-256301\n- **Principal:** 04994-250290\n- **Director (LBS Centre):** 0471-2324396\n\n### Email Addresses\n- **Principal:** principal@lbscek.ac.in\n- **Office:** office@lbscek.ac.in\n- **Admission:** admission@lbscek.ac.in\n- **Administrative Officer:** administrativeofficer@lbscek.ac.in\n- **CGPU (Placements):** cgpu@lbscek.ac.in\n- **Hostel Warden:** warden@lbscek.ac.in\n- **Library:** library@lbscek.ac.in\n- **CSE Department:** csed@lbscek.ac.in\n- **ME Department:** med@lbscek.ac.in\n- **EEE Department:** eed@lbscek.ac.in\n- **CE Department:** ced@lbscek.ac.in\n- **Director:** director.lbs@kerala.gov.in\n\n### Website\n- **Official:** https://lbscek.ac.in/\n- **LBS Centre:** http://www.lbscentre.kerala.gov.in/', 29)

ON CONFLICT (section_key) DO UPDATE
SET content = EXCLUDED.content,
    section_title = EXCLUDED.section_title,
    section_order = EXCLUDED.section_order;
