-- ============================================
-- Create chat_analytics table
-- Tracks every chat interaction for usage dashboards
-- ============================================

CREATE TABLE IF NOT EXISTS chat_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL,
  detected_language TEXT DEFAULT 'english',
  response_time_ms INT,
  tokens_used INT,
  was_answered BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for time-based aggregation queries
CREATE INDEX IF NOT EXISTS idx_analytics_created ON chat_analytics(created_at);

-- RLS: service role can read/write, anon can read for dashboard
ALTER TABLE chat_analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access" ON chat_analytics
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Anon can read analytics" ON chat_analytics
  FOR SELECT USING (true);
