-- ============================================
-- Create unanswered_questions table
-- Stores user questions the bot couldn't answer
-- Used by resolve-questions function to auto-find answers
-- ============================================

CREATE TABLE IF NOT EXISTS unanswered_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  detected_language TEXT DEFAULT 'english',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolving', 'resolved', 'unresolvable')),
  resolved_answer TEXT,
  resolved_section_key TEXT,
  source_url TEXT,
  attempts INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

-- Index for quick lookup of pending questions
CREATE INDEX IF NOT EXISTS idx_unanswered_status ON unanswered_questions(status);

-- Deduplication index: don't store the exact same question twice
CREATE UNIQUE INDEX IF NOT EXISTS idx_unanswered_question_unique 
  ON unanswered_questions(md5(question)) 
  WHERE status = 'pending';

-- RLS: service role can read/write, anon can insert only
ALTER TABLE unanswered_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access" ON unanswered_questions
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Anon can insert questions" ON unanswered_questions
  FOR INSERT WITH CHECK (true);

-- ============================================
-- Add cron job for resolve-questions
-- Runs 30 minutes after sync-knowledge (22:00 UTC = 3:30 AM IST)
-- ============================================
SELECT cron.schedule(
  'resolve-unanswered-questions',
  '0 22 * * *',
  $$
  SELECT net.http_post(
    url := 'https://hrbrbxebpxlticknrpuw.supabase.co/functions/v1/resolve-questions',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyYnJieGVicHhsdGlja25ycHV3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTcxMjU3NywiZXhwIjoyMDU1Mjg4NTc3fQ.service_role_key_here'
    ),
    body := '{}'::jsonb
  );
  $$
);
